language: node_js
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
env: 
  - CXX=g++-5
node_js:
    - "0.12"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
