language: node_js
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
env: CXX=g++-4.9
node_js:
    - "0.12"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
