image:
  - "Visual Studio 2017"
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - git submodule update --init --recursive
  - npm install -g npm
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
